# Generated by Django 4.2.7 on 2025-08-19 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0002_alter_calculationhistory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculationhistory',
            name='risk_per_quantity',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='calculationhistory',
            name='targets',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='calculationhistory',
            name='direction',
            field=models.CharField(choices=[('Buy (Long)', 'Buy (Long)'), ('Sell (Short)', 'Sell (Short)'), ('LONG', 'Long'), ('SHORT', 'Short')], default='Buy (Long)', max_length=15),
        ),
        migrations.AlterField(
            model_name='calculationhistory',
            name='risk_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
