# Generated by Django 4.2.7 on 2025-08-21 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0003_calculationhistory_risk_per_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20, unique=True)),
                ('company_name', models.CharField(max_length=200)),
                ('last_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('change', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pchange', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('volume', models.BigIntegerField(default=0)),
                ('market_cap', models.BigIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Stock Data',
                'verbose_name_plural': 'Stock Data',
                'ordering': ['symbol'],
            },
        ),
    ]
